<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EPBYMINW1753" name="ViewCar" tests="2" failures="1" timestamp="29 Nov 2015 19:38:30 GMT" time="0.01" errors="0">
  <testcase name="SelectACar" time="0.0" classname="by.epam.tat.cherevach.module4.task1.unit_testing.TestSelectACar">
    <failure type="org.testng.TestException" message="
Method TestSelectACar.SelectACar(java.lang.String)[pri:0, instance:by.epam.tat.cherevach.module4.task1.unit_testing.TestSelectACar@161cd475] should have thrown an exception of type class by.epam.tat.cherevach.module3.lecture3.task1.exceptions.CarNotFoundExc">
      <![CDATA[org.testng.TestException: 
Method TestSelectACar.SelectACar(java.lang.String)[pri:0, instance:by.epam.tat.cherevach.module4.task1.unit_testing.TestSelectACar@161cd475] should have thrown an exception of type class by.epam.tat.cherevach.module3.lecture3.task1.exceptions.CarNotFoundExc
	at by.epam.tat.cherevach.module4.task1.unit_testing.UnitTestRunner.main(UnitTestRunner.java:17)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- SelectACar -->
  <testcase name="SelectACar2" time="0.0" classname="by.epam.tat.cherevach.module4.task1.unit_testing.TestSelectACar"/>
</testsuite> <!-- ViewCar -->
